init:
    python -m venv .venv
    .venv/bin/python -m pip install --upgrade pip wheel setuptools
    .venv/bin/python -m pip install -r requirements.txt
    @echo "Run the following command to activate the virtual environment:"
    @echo ""
    @echo "source .venv/bin/activate"
    
write-manifest:
    .venv/bin/rsconnect write-manifest notebook \
        --overwrite \
        model_training_deployment.ipynb